<h3>Handling Observable Errors</h3>

<ol><li><code>Observable.subscribe</code> accepts three methods as parameters</li><li>The first method is the <code>next</code> handler that gets fired when the underlying data changes</li><li>The second method is the <code>error</code> handler that gets fired when there is an error in the observable sequence</li><li>The third method is the <code>complete</code> handler that gets fired when the observable sequence is completed</li><li>We will use <code>Observable.catch</code> to recover and continue the observable sequence that is terminated by an exception</li></ol>
